project:
  type: website

website:
  title: "Sleep Efficiency Project"
  navbar:
    background: "#003366"   # Dark blue for contrast and professionalism
    foreground: "#FFFFFF"   # White text
    left:
      - text: "HOME"
        file: index.qmd
      - text: "ANALYSIS"
        file: analysis.qmd
      - text: "MODEL"
        file: model.qmd
      - text: "ABOUT"
        file: about.qmd
format:
  html:
    theme: cosmo  # Optional stylish theme
    css: styles.css  # Optional: your custom CSS for extra polish
