project:
  type: website

website:
  title: "Sleep Efficiency Project"
  navbar:
    background: "#003366"
    foreground: "#FFFFFF"
    left:
      - text: "HOME"
        file: index.qmd
      - text: "ANALYSIS"
        file: analysis.qmd
      - text: "MODEL"
        file: model.qmd
      - text: "ABOUT"
        file: about.qmd
      - text: "SOURCE"
        file: source.qmd

format:
  html:
    theme: cosmo
    css: styles.css
